version: "3.8"

services:
  fuseki:
    build: .
    container_name: inf6083_fuseki
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}
    volumes:
      - fuseki_data:/fuseki/databases
    restart: unless-stopped

volumes:
  fuseki_data: